name: signalr_core
description: ASP.NET Core SignalR Client.
version: 1.0.0
Homepage: https://github.com/jamiewest/signalr_core
author: Jamie West

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  http: ^0.12.0+2
  logging: ^0.11.3+2
  tuple: ^1.0.3
  web_socket_channel: ^1.1.0
  sse_client: ^0.0.1

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
